name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check delectory
        run : ls -la
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Check python version
        run : python --version 
      - name: install ruff
        run : pip install ruff==0.1.9
      - name: check ruff version
        run : ruff --version
      - name: run ruff check
        run : ruff check .